name: Sync

on:
  workflow_dispatch: # or on a schedule
  # or trigger from a webhook via GitHub App, if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone private repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_ACTION_SYNC_PAT }}@github.com/your-org/optici.git
          cp -r optici/github.action.testselection/* .
      
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync"
            git push
          else
            echo "No changes"
          fi