name: Sync

on:
  workflow_dispatch: # or on a schedule
  # or trigger from a webhook via GitHub App, if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone private repo
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://x-access-token:${{ secrets.GH_ACTION_SYNC_PAT }}@github.com/OptiCI/optici.git private
          mkdir temp-copy
          cd private
          git sparse-checkout set github.action.testselection
          cp -r github.action.testselection/* ../temp-copy/
          cd ..

      - name: Clean public repo (except .github)
        run: |
          shopt -s extglob
          rm -rf !(temp-copy|.git|.github)
          mv temp-copy/* .
    
      - name: Verify token has repo access
        env:
          TOKEN: ${{ secrets.GH_ACTION_SYNC_PAT }}
        run: |
          curl -s -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/OptiCI/optici-select-tests \
            | jq '.permissions'

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync"
            git status
            git branch
            git remote -v
            git push https://x-access-token:${{ secrets.GH_ACTION_SYNC_PAT }}@github.com/OptiCI/optici-select-tests.git HEAD:main
          else
            echo "No changes"
          fi